// Package codexbridge contains the state bindings for a Codex app-server
// adapter. It does not start Codex, perform inference, or execute tools.
package codexbridge

import (
	"bytes"
	"encoding/json"
	"errors"
	"reflect"
	"regexp"
	"strings"
	"sync"
	"unicode/utf8"

	"github.com/ArronJablonowski/DarwinRouter/providers"
)

var ErrContinuation = errors.New("codex bridge: invalid tool continuation")

const maxExchangeBytes = 8 << 20

var namePattern = regexp.MustCompile(`^[a-zA-Z0-9_-]{1,64}$`)

// CallRequest is the experimental item/tool/call parameter shape generated by
// Codex CLI 0.153.4. RPC request IDs belong to the transport, not CallID.
type CallRequest struct {
	Arguments json.RawMessage `json:"arguments"`
	CallID    string          `json:"callId"`
	Namespace string          `json:"namespace"`
	ThreadID  string          `json:"threadId"`
	Tool      string          `json:"tool"`
	TurnID    string          `json:"turnId"`
}

// Pending binds a paused server tool request to the exact Darwin inference
// history that produced it. The host must keep the server request unanswered
// until its runtime has persisted and authorized the proposal and its result.
// This binding verifies correspondence, NOT approval or durable persistence.
// A failed/uncertain tool must abort the server turn, not resume this exchange.
type Pending struct {
	mu       sync.Mutex
	request  providers.Request
	text     string
	call     providers.ToolCall
	resolved bool
}

// NewPending admits only tools explicitly supplied by Darwin under the darwin
// namespace. Built-in tools and other namespaces cannot become proposals here.
// This is not a substitute for disabling those tools in the subprocess.
func NewPending(req providers.Request, threadID, turnID, text string, call CallRequest) (*Pending, error) {
	if !validRequest(req) || providers.ValidateMessages(req.Messages) != nil ||
		!utf8.ValidString(text) || !utf8.ValidString(call.CallID) || !utf8.Valid(call.Arguments) ||
		threadID == "" || turnID == "" || call.ThreadID != threadID || call.TurnID != turnID ||
		call.Namespace != "darwin" || !namePattern.MatchString(call.Tool) ||
		call.CallID == "" || len(call.CallID) > 256 || strings.ContainsAny(call.CallID, "\r\n\x00") ||
		len(text) > maxExchangeBytes || len(call.Arguments) > 16<<10 || !json.Valid(call.Arguments) ||
		!bytes.HasPrefix(bytes.TrimSpace(call.Arguments), []byte("{")) {
		return nil, ErrContinuation
	}
	matched := false
	names := make(map[string]bool, len(req.Tools))
	for _, tool := range req.Tools {
		if !namePattern.MatchString(tool.Name) || names[tool.Name] {
			return nil, ErrContinuation
		}
		names[tool.Name] = true
		matched = matched || tool.Name == call.Tool
	}
	if !matched || req.Model == "" || len(req.Messages) == 0 {
		return nil, ErrContinuation
	}
	for _, message := range req.Messages {
		for _, prior := range message.ToolCalls {
			if prior.ID == call.CallID {
				return nil, ErrContinuation
			}
		}
		if message.ToolCallID == call.CallID {
			return nil, ErrContinuation
		}
	}
	// Own all caller-provided slices. JSON also rejects invalid schema/argument
	// fragments. The byte ceiling applies to history plus catalog together.
	b, err := json.Marshal(req)
	if err != nil || len(b)+len(text)+len(call.Arguments) > maxExchangeBytes {
		return nil, ErrContinuation
	}
	var owned providers.Request
	if json.Unmarshal(b, &owned) != nil {
		return nil, ErrContinuation
	}
	return &Pending{request: owned, text: text, call: providers.ToolCall{
		ID: call.CallID, Name: call.Tool, Arguments: bytes.Clone(call.Arguments),
	}}, nil
}

// Proposal returns owned bytes; mutating the return value cannot change the
// expected assistant/tool pair. No side effect is performed by this method.
func (p *Pending) Proposal() providers.ToolCall {
	c := p.call
	c.Arguments = bytes.Clone(c.Arguments)
	return c
}

// Resume accepts only the original request followed by the exact assistant
// proposal and one successful tool result. The existing runtime only appends
// tool messages after successful durable completion. Steering, compaction,
// model/catalog changes and retry reconstruction require separate handling;
// they must not silently mutate a paused Codex turn. A successful call is
// single-use even if delivery of the returned RPC response later fails.
func (p *Pending) Resume(next providers.Request) (json.RawMessage, error) {
	p.mu.Lock()
	defer p.mu.Unlock()
	if p.resolved || len(next.Messages) != len(p.request.Messages)+2 || !validRequest(next) || providers.ValidateMessages(next.Messages) != nil {
		return nil, ErrContinuation
	}
	b, err := json.Marshal(next)
	if err != nil || len(b) > maxExchangeBytes {
		return nil, ErrContinuation
	}
	var owned providers.Request
	if json.Unmarshal(b, &owned) != nil {
		return nil, ErrContinuation
	}
	n := len(p.request.Messages)
	assistant, result := owned.Messages[n], owned.Messages[n+1]
	owned.Messages = owned.Messages[:n]
	want := providers.Message{Role: "assistant", Content: p.text, ToolCalls: []providers.ToolCall{p.call}}
	// Compare the same canonical JSON representation used for the snapshot:
	// RawMessage whitespace is normalized by Marshal, while values/order stay
	// bound. Never compare only a caller-provided digest or tool name.
	wantBytes, _ := json.Marshal(want)
	gotBytes, _ := json.Marshal(assistant)
	if !reflect.DeepEqual(owned, p.request) || !bytes.Equal(wantBytes, gotBytes) ||
		result.Role != "tool" || result.ToolCallID != p.call.ID || len(result.ToolCalls) != 0 {
		return nil, ErrContinuation
	}
	response, err := json.Marshal(struct {
		ContentItems []map[string]string `json:"contentItems"`
		Success      bool                `json:"success"`
	}{[]map[string]string{{"type": "inputText", "text": result.Content}}, true})
	if err != nil {
		return nil, ErrContinuation
	}
	p.resolved = true
	return response, nil
}
