package quality

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestSourceGates(t *testing.T) {
	for _, tc := range []struct {
		name, source, finding string
	}{
		{"clean", "package example\n", ""},
		{"boundary", "package example\n\n" + strings.Repeat("// line\n", 998), ""},
		{"oversize", "package example\n" + strings.Repeat("// line\n", 1000), "exceeds limit"},
		{"unterminated last line", "package example\n" + strings.Repeat("// line\n", 999) + "// last", "exceeds limit"},
		{"format", "package example\nfunc Example(){ }\n", "run gofmt"},
		{"invalid", "package ?\n", "invalid Go source"},
		{"generated", "// Code generated by fixture. DO NOT EDIT.\npackage example\n" + strings.Repeat("// line\n", 1001), ""},
	} {
		t.Run(tc.name, func(t *testing.T) {
			root := t.TempDir()
			if err := os.WriteFile(filepath.Join(root, "fixture.go"), []byte(tc.source), 0600); err != nil {
				t.Fatal(err)
			}
			findings, err := Check(root)
			if err != nil {
				t.Fatal(err)
			}
			if tc.finding == "" && len(findings) != 0 {
				t.Fatalf("unexpected findings: %v", findings)
			}
			if tc.finding != "" && !strings.Contains(strings.Join(findings, "\n"), tc.finding) {
				t.Fatalf("missing %q in %v", tc.finding, findings)
			}
		})
	}
}

func TestVendorExcluded(t *testing.T) {
	root := t.TempDir()
	if err := os.Mkdir(filepath.Join(root, "vendor"), 0700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, "vendor", "bad.go"), []byte("invalid"), 0600); err != nil {
		t.Fatal(err)
	}
	findings, err := Check(root)
	if err != nil || len(findings) != 0 {
		t.Fatalf("vendor not excluded: %v %v", findings, err)
	}
}
